---
plugins:
  - jest

env:
  node: true
  jest: true

extends:
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]